global:
  save_path: ./output

model:
  name: Qwen # angelslim model name
  model_path: Qwen/Qwen3-4B # your model path or hf model name
  trust_remote_code: true
  torch_dtype: auto
  device_map: auto
  low_cpu_mem_usage: true
  use_cache: false

compression:
  name: QAT
  quantization:
    name: w4a8_fp8 # or fp8_static or fp8_dynamic
    bits: 8
    quant_method:
      weight: per-group # or per-tensor
      activation: per-tensor
      group_size: 128 # or -1
    ignore_layers: ["lm_head", "embed_tokens"] # Skip quantization for these layers

dataset:
  name: TextDataset
  data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
  max_seq_length: 2048
  num_samples: 256
  batch_size: 1

# QAT-specific configuration
training:
  hf_dataset: Salesforce/wikitext,wikitext-2-raw-v1 # hf dataset name
  cache_dir: None # your cache path
  max_length: 2048
  training_mode: end2end  # or blockwise
  dist_mode: hf # "hf" is using hf Trainer
  save_format: fake # real or ''(not set for skip)
  do_train: true
  resume_ckpt_dir: '' # resume for fake checkpoint, when save_format=='fake'
  plugin_config:
    enable_scale: true
    quant_config:
      use_weight_quant: true
      use_activation_quant: true
      lazy_init_samples: 60
      weight: # can overwrite compression.quantization
        qtype: int8
        granularity: per-tensor
        group_size: 128
        is_sym: true
      activation: # can overwrite compression.quantization
        qtype: int8
        granularity: per-tensor
        is_sym: true
        dynamic: false
  hf_args: # hf trainer args
    output_dir: ./output
    logging_steps: 1
    logging_first_step: true
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 16
    learning_rate: 1e-3
    lr_scheduler_type: constant
    num_train_epochs: 1

